
name: Run API Tests

on: [push, pull_request]
# on:
#   schedule:
#     - cron: '0 22 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Playwright
        run: npx playwright install --with-deps && npm install @playwright/tests
