
name: Run Playwright Tests

on: [push, pull_request]
# on:
#   schedule:
#     - cron: '0 22 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install package.json NPM
        run: npm install

      # - name: Install Playwright
      #   run: npx playwright install --with-deps

      # - name: Run Playwright cucumber tests
      #   run: npx cucumber-js
      #   continue-on-error: true

      # - name: Upload Report 
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: newman-report
      #     path: newman/report.html